version: '3.8'

services:
  # Your application in production
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: mergers-acquisitions-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - LOG_LEVEL=info
      # DATABASE_URL should be provided via environment variables or .env.production
      # This connects directly to Neon Cloud
      - DATABASE_URL=${DATABASE_URL}
      - ARCJET_KEY=${ARCJET_KEY}
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => { process.exit(1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security settings for production
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    # Resource limits for production
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Logging configuration for production
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
